### ISSUE TITLE
GriefPrevention protection and Magical Eye Of Ender cause infinity ender pearls

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/CS-CoreLib2#155]
## Description (Required)

When you use the Magical Eye Of Ender to teleport to or in Greifprevention protection the Girefprevention add ender pearl to the inventory.

## Steps to reproduce the Issue (Required)

https://www.youtube.com/watch?v=JZknXt380Fw

## Expected behavior (Required)

Maybe the CS-CoreLib2 could remove the added ender pearl from inventory or not add ender pearl to inventory.

Purpur git-Purpur-993 (MC: 1.16.5)
Slimefun DEV - 822 (git c4be51f7)
Metrics-Module #21
Java 11

No Addons installed

## FULL plugins list (Required)

Plugins (14): Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, GriefPrevention, LuckPerms, Multiverse-Core, PlugMan, ProtocolLib, SafeNBT, Slimefun, Vault, WorldEdit, WorldGuard

**Comment by TheBusyBiscuit** [comment]
This will not be an easy fix.
It will likely need to be patched from both sides, within GriefPrevention and Slimefun itself.
I have reached out to the GriefPrevention developer to discuss a best approach.

**Comment by TheBusyBiscuit** [comment]
Disucssed with the GriefPrevention developer and you should open an issue about it on their bug tracker instead:
https://github.com/TechFortress/GriefPrevention/issues
