### ISSUE TITLE
Slimefun, Blocklocker incompatibility. 

### ISSUE THREAD

**Issue by GenericEntity579** [TheBusyBiscuit/CS-CoreLib2#35]
https://pastebin.com/ZPc35TWt

Affiliated plugins:
BlockLocker v1.7
CS-CoreLib vDEV - 78 (git 199e1b1e)
Slimefun vRC - 3 (git 8a605404)

Paper v1_14_R1
Minecraft 1.14.4

Symptoms:
Slimefun machines broken.
Console spam of posted error.

Errors start spamming as soon as someone tries to use a Slimefun machine.

**Comment by TheBusyBiscuit** [comment]
Post errors via pastebin... Not like this...
