### ISSUE TITLE
An Error occured while querying the Protection Module: "GriefPrevention"

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/CS-CoreLib2#50]
## Description (Required)

An Error occured while querying the Protection Module: "GriefPrevention"

## Steps to reproduce the Issue (Required)

I don't know. I find this error on console. Maybe cause this the StormStaff items from Slimefun plugin.

## Expected behavior (Required)

No write this error

## Server Log / Error Report

https://pastebin.com/9NNHHZgd

## Environment (Required)

 - Minecraft Version: 1.15.1
 - CS-CoreLib Version: vDEV - 80 (git e3242c60)

**Comment by TheBusyBiscuit** [comment]
What's your Slimefun and GriefPrevention version...?

**Comment by andris155** [comment]
Slimefun: vDEV - 408 (git 73b64e87)
GriefPrevention:  16.12.0-d4d7ac4
