### ISSUE TITLE
Slimefun Block Placer can place blocks to the PlotSquared plot wall, and protected regions

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/CS-CoreLib2#96]
## Description (Required)

Slimefun Block Placer can place blocks to the PlotSquared protected plot wall.
Slimefun Block Placer can place blocks to the WorldGuard protection.
Slimefun Block Placer can place blocks to the Griefprevention protection.

## Steps to reproduce the Issue (Required)

1. Give and place an Block Placer near the PlotSquared road or near protected region.
2. Put a block to Block Placer.
3. Activate the Block Placer.

![2020-07-26_22 59 29](https://user-images.githubusercontent.com/8324198/88489392-40f30800-cf94-11ea-8e50-45885638d97c.png)

![2020-07-26_23 08 54](https://user-images.githubusercontent.com/8324198/88489680-0d18e200-cf96-11ea-9a91-7fae81e31645.png)

![2020-07-26_23 14 02](https://user-images.githubusercontent.com/8324198/88489687-1144ff80-cf96-11ea-8114-4767602f8587.png)

## Expected behavior (Required)

Slimefun Block Placer can't place to blocks to the PlotSquared plot wall.
Slimefun Block Placer can't place blocks to the WorldGuard protection.
Slimefun Block Placer can't place blocks to the Griefprevention protection.

## Server specs (Required)

 - Server Software: Paper
 - Minecraft Version: 1.16.1
 - Slimefun Version: vDEV - 600 (git 63569fac)
 - CS-CoreLib Version: vDEV - 90 (git 9dd4a1cf)
 - PlotSquared version: 5.13.0-Premium
 - GriefPrevention version: 16.14.0
 - WorldGuard version 7.0.4-beta1;bc551da

## FULL plugins list (Required)

Plugins (14): CS-CoreLib, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, LuckPerms, Multiverse-Core, PlotSquared, PlugMan, ProtocolLib, Slimefun, Vault, WorldEdit, WorldGuard

**Comment by TheBusyBiscuit** [comment]
This one would probably belong onto Slimefuns bug tracker actually since I dont think the Block Placer supports protection plugins at all.
It doesn't place those blocks in the name of any player, so that would just be  hard to implement anyway.
